/**
 * Created by Bogdan on 8/2/2016.
 */
export const NEWS_SELECTED = 'NEWS_SELECTED'
export const GET_SPECIFIC_NEWS_REQUEST ='GET_SPECIFIC_NEWS_REQUEST'
export const GET_SPECIFIC_NEWS_SUCCES ='GET_SPECIFIC_NEWS_SUCCES'